### ISSUE TITLE
Fix conference contacts info

### ISSUE THREAD

**Issue by aywander** [TheoreticalAstrophysicsGroup/TheoreticalAstrophysicsGroup.github.io#194]
conference contact info has been changed to

``` yaml
contact:
  name:
  email:
  message:
```

see `_include/aside_conf.html`

Reflect this change in the entries.
